import AsyncStorage from '@react-native-async-storage/async-storage';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { StatusBar } from 'expo-status-bar';
import { useEffect, useMemo, useRef, useState, startTransition } from 'react';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { ActivityIndicator, Alert, SafeAreaView, Text, TextInput } from 'react-native';

import {
  baseFontFamily,
  flowOptions,
  moodPresets,
  painOptions,
  symptomCatalog,
} from './src/features/cycleTracker/constants';
import {
  buildUnconfiguredDayMeta,
  hasCustomEntryContent,
  parseStoredProfile,
  parseStoredMedicalReminders,
  sanitizeAutoGeneratedRecord,
  sortRecords,
} from './src/features/cycleTracker/helpers';
import { useCycleRecords } from './src/features/cycleTracker/hooks/useCycleRecords';
import { useCycleProfile } from './src/features/cycleTracker/hooks/useCycleProfile';
import { useMedicalReminders } from './src/features/cycleTracker/hooks/useMedicalReminders';
import { useAppLock } from './src/features/cycleTracker/hooks/useAppLock';
import { DayEntryScreen } from './src/features/cycleTracker/screens/DayEntryScreen';
import { MainDashboardScreen } from './src/features/cycleTracker/screens/MainDashboardScreen';
import { OnboardingScreen } from './src/features/cycleTracker/screens/OnboardingScreen';
import {
  CalendarFocusMode,
  PeriodMarkMode,
} from './src/features/cycleTracker/types';
import {
  averagePain,
  buildMonthMatrix,
  createElapsedPredictedPeriodRecords,
  deriveEstimatedProfile,
  differenceInDays,
  formatDateLongWithYear,
  formatMonthLabel,
  formatFrenchDateTyping,
  getCycleDay,
  getCyclePhase,
  getDaysUntilNextPeriod,
  getFertileWindow,
  getPeriodLengthAverage,
  getPeriodRuns,
  getRelativeEnergy,
  getUpcomingPeriodStart,
  isoDate,
  monthOffset,
  resolveDayMetaForRecord,
  toDate,
} from './src/lib/cycle';
import {
  averageSleep,
  countPeriodEntries,
  getFlowAnomalies,
  getFlowDistribution,
  getDominantSymptoms,
  getMonthComparison,
  getMonthlyHistory,
  getPainTrend,
  getRecentRecords,
} from './src/lib/insights';
import {
  CYCLE_PROFILE_STORAGE_KEY,
  CYCLE_RECORDS_STORAGE_KEY,
  MEDICAL_REMINDERS_STORAGE_KEY,
  LAST_PERIOD_REFERENCE_CONFIRMED_STORAGE_KEY,
} from './src/lib/storage';
import {
  getPregnancyDueDateLabel,
  getPregnancyStage,
  getPregnancyWeekFromDueDate,
  getPregnancyWeeksRemainingLabel,
} from './src/features/cycleTracker/pregnancy';
import AppDataContext from './src/features/cycleTracker/context/AppDataContext';
import { useColors } from './src/styles/useAppStyles';
import { ErrorBoundary } from './src/components/ErrorBoundary';
import { LockScreen } from './src/components/LockScreen';
import { exportCycleData } from './src/lib/export';
import { pickAndParseCsv } from './src/lib/import';
import { requestNotificationPermissions } from './src/lib/notifications';
import { ThemeProvider, useTheme } from './src/styles/ThemeContext';
import { styles } from './src/styles/appStyles';

type RootStackParamList = {
  Home: undefined;
  DayEntry: undefined;
};

const Stack = createNativeStackNavigator<RootStackParamList>();

function AppRoot() {
  const [todayIso] = useState(isoDate(new Date()));
  const [isPeriodSelectionMode, setIsPeriodSelectionMode] = useState(false);
  const [periodMarkMode, setPeriodMarkMode] = useState<PeriodMarkMode>('single');
  const [calendarFocusMode, setCalendarFocusMode] = useState<CalendarFocusMode>('all');
  const [periodRangeAnchor, setPeriodRangeAnchor] = useState<string | null>(null);
  const [periodRangePreviewEnd, setPeriodRangePreviewEnd] = useState<string | null>(null);
  const [selectedDate, setSelectedDate] = useState(todayIso);
  const [monthCursor, setMonthCursor] = useState(0);
  const [isHydrated, setIsHydrated] = useState(false);

  const cycleRecords = useCycleRecords();
  const cycleProfile = useCycleProfile();
  const medRem = useMedicalReminders();
  const appLock = useAppLock();
  const c = useColors();
  const { scheme: themeScheme, toggleTheme: onToggleTheme } = useTheme();

  // — Notification permissions (fire-and-forget, non-blocking) —
  useEffect(() => { void requestNotificationPermissions(); }, []);

  // — Font setup —
  useEffect(() => {
    const textComponent = Text as typeof Text & { defaultProps?: { style?: object | object[] } };
    const inputComponent = TextInput as typeof TextInput & { defaultProps?: { style?: object | object[] } };
    textComponent.defaultProps = textComponent.defaultProps ?? {};
    inputComponent.defaultProps = inputComponent.defaultProps ?? {};
    textComponent.defaultProps.style = [{ fontFamily: baseFontFamily }, textComponent.defaultProps.style ?? {}];
    inputComponent.defaultProps.style = [{ fontFamily: baseFontFamily }, inputComponent.defaultProps.style ?? {}];
  }, []);

  // — Hydration —
  useEffect(() => {
    async function hydrateApp() {
      try {
        const [
          storedRecords,
          storedProfile,
          storedMedicalReminders,
          storedLastPeriodReferenceConfirmed,
        ] = await Promise.all([
          AsyncStorage.getItem(CYCLE_RECORDS_STORAGE_KEY),
          AsyncStorage.getItem(CYCLE_PROFILE_STORAGE_KEY),
          AsyncStorage.getItem(MEDICAL_REMINDERS_STORAGE_KEY),
          AsyncStorage.getItem(LAST_PERIOD_REFERENCE_CONFIRMED_STORAGE_KEY),
        ]);

        const referenceConfirmed = storedLastPeriodReferenceConfirmed === 'true';

        if (storedRecords) {
          const parsedRecords = JSON.parse(storedRecords) as import('./src/data/cycleData').CycleRecord[];
          if (Array.isArray(parsedRecords)) {
            const normalizedRecords = parsedRecords.map((record) =>
              record.source === 'manual' ? record : sanitizeAutoGeneratedRecord(record)
            );
            const hasUserRecordedPeriod = normalizedRecords.some(
              (record) => record.flow !== 'Absent' && record.source !== 'inferred'
            );
            const sanitizedRecords =
              referenceConfirmed || hasUserRecordedPeriod
                ? normalizedRecords
                : normalizedRecords.filter((record) => record.source !== 'inferred');

            const sorted = sortRecords(sanitizedRecords);
            cycleRecords.initialize(sorted);

            if (JSON.stringify(sanitizedRecords) !== JSON.stringify(parsedRecords)) {
              await AsyncStorage.setItem(CYCLE_RECORDS_STORAGE_KEY, JSON.stringify(sorted));
            }
          }
        }

        const parsedProfile = parseStoredProfile(storedProfile);
        cycleProfile.initialize(parsedProfile, referenceConfirmed);
        medRem.initialize(parseStoredMedicalReminders(storedMedicalReminders));
      } catch {
        cycleRecords.setEntryMessage('Impossible de charger les données locales.');
      } finally {
        setIsHydrated(true);
      }
    }

    void hydrateApp();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // — Entry form sync —
  useEffect(() => {
    cycleRecords.syncEntryFormToDate(selectedDate, cycleRecords.recordMap);
  }, [cycleRecords.records, selectedDate]); // eslint-disable-line react-hooks/exhaustive-deps

  // — Infer elapsed periods —
  // records ref keeps the latest records value without triggering the inference effect on each record change.
  const recordsRef = useRef(cycleRecords.records);
  useEffect(() => { recordsRef.current = cycleRecords.records; }, [cycleRecords.records]);

  const inferenceRanRef = useRef(false);
  useEffect(() => { inferenceRanRef.current = false; }, [cycleProfile.hasConfirmedLastPeriodReference, cycleProfile.profile]);

  useEffect(() => {
    if (inferenceRanRef.current) return;

    async function inferElapsedPeriods() {
      const { profile, hasConfirmedLastPeriodReference } = cycleProfile;
      const records = recordsRef.current;

      const hasReferenceNow =
        (hasConfirmedLastPeriodReference && Boolean(profile?.lastPeriodStart)) ||
        Boolean(getPeriodRuns(records.filter((r) => r.source !== 'inferred')).length);

      if (!isHydrated || !profile || !hasReferenceNow) return;

      const inferredRecords = createElapsedPredictedPeriodRecords(
        todayIso,
        deriveEstimatedProfile(profile, records),
        records
      );

      inferenceRanRef.current = true;
      if (inferredRecords.length) {
        await cycleRecords.persistRecords([...records, ...inferredRecords]);
      }
    }

    void inferElapsedPeriods();
  }, [cycleProfile.hasConfirmedLastPeriodReference, isHydrated, cycleProfile.profile, todayIso]); // eslint-disable-line react-hooks/exhaustive-deps

  // — Derived state —
  const { records, recordMap, entryForm, entryMessage } = cycleRecords;
  const { profile, profileForm, profileMessage, hasConfirmedLastPeriodReference, onboardingStep, trackingSetupMessage } = cycleProfile;

  const today = useMemo(() => toDate(todayIso), [todayIso]);
  const isProfileConfigured = profile !== null;
  const userRecordedPeriodStart = useMemo(
    () => getPeriodRuns(records.filter((r) => r.source !== 'inferred')).at(-1)?.start ?? null,
    [records]
  );
  const knownLastPeriodStart =
    userRecordedPeriodStart ??
    (hasConfirmedLastPeriodReference ? profile?.lastPeriodStart || null : null);
  const effectiveTrackingMode = profile?.trackingMode ?? 'cycle';
  const isPregnancyMode = effectiveTrackingMode === 'pregnancy';
  const hasCycleReference = !isPregnancyMode && Boolean(knownLastPeriodStart);
  const effectiveProfile = useMemo(
    () => ({
      name: profile?.name ?? '',
      trackingMode: profile?.trackingMode ?? 'cycle',
      cycleLength: profile?.cycleLength ?? 28,
      periodLength: profile?.periodLength ?? 5,
      lastPeriodStart: knownLastPeriodStart ?? todayIso,
      addressingStyle: profile?.addressingStyle ?? 'nonBinary',
      pregnancyDueDate: profile?.pregnancyDueDate ?? '',
    }),
    [knownLastPeriodStart, profile, todayIso]
  );
  const estimatedProfile = useMemo(
    () => (isProfileConfigured ? deriveEstimatedProfile(effectiveProfile, records) : effectiveProfile),
    [effectiveProfile, isProfileConfigured, records]
  );
  const currentMonthDate = useMemo(() => monthOffset(today, monthCursor), [today, monthCursor]);
  const monthLabel = useMemo(() => formatMonthLabel(currentMonthDate), [currentMonthDate]);
  const selectedRecord = useMemo(() => recordMap.get(selectedDate), [recordMap, selectedDate]);
  const monthComparison = useMemo(() => getMonthComparison(records), [records]);
  const nextPeriodStart = useMemo(
    () => getUpcomingPeriodStart(todayIso, estimatedProfile.lastPeriodStart, estimatedProfile.cycleLength),
    [estimatedProfile.cycleLength, estimatedProfile.lastPeriodStart, todayIso]
  );
  const nextPeriodInDays = useMemo(
    () => getDaysUntilNextPeriod(todayIso, estimatedProfile.lastPeriodStart, estimatedProfile.cycleLength),
    [estimatedProfile.cycleLength, estimatedProfile.lastPeriodStart, todayIso]
  );
  const fertileWindow = useMemo(
    () => getFertileWindow(todayIso, estimatedProfile.lastPeriodStart, estimatedProfile.cycleLength),
    [estimatedProfile.cycleLength, estimatedProfile.lastPeriodStart, todayIso]
  );
  const todayCycleDay = useMemo(
    () => getCycleDay(todayIso, estimatedProfile.lastPeriodStart, estimatedProfile.cycleLength),
    [estimatedProfile.cycleLength, estimatedProfile.lastPeriodStart, todayIso]
  );
  const todayCyclePhase = useMemo(
    () => getCyclePhase(todayCycleDay, estimatedProfile.cycleLength, estimatedProfile.periodLength),
    [estimatedProfile.cycleLength, estimatedProfile.periodLength, todayCycleDay]
  );
  const cycleDay = useMemo(
    () => getCycleDay(selectedDate, estimatedProfile.lastPeriodStart, estimatedProfile.cycleLength),
    [estimatedProfile.cycleLength, estimatedProfile.lastPeriodStart, selectedDate]
  );
  const cyclePhase = useMemo(
    () => getCyclePhase(cycleDay, estimatedProfile.cycleLength, estimatedProfile.periodLength),
    [cycleDay, estimatedProfile.cycleLength, estimatedProfile.periodLength]
  );
  const pregnancyWeek = useMemo(() => {
    if (!isPregnancyMode || !effectiveProfile.pregnancyDueDate) return 1;
    return getPregnancyWeekFromDueDate(effectiveProfile.pregnancyDueDate, todayIso);
  }, [effectiveProfile.pregnancyDueDate, isPregnancyMode, todayIso]);
  const pregnancyStage = useMemo(() => getPregnancyStage(pregnancyWeek), [pregnancyWeek]);
  const pregnancyDueDateLabel = useMemo(
    () => getPregnancyDueDateLabel(effectiveProfile.pregnancyDueDate),
    [effectiveProfile.pregnancyDueDate]
  );
  const pregnancyWeeksRemainingLabel = useMemo(
    () => getPregnancyWeeksRemainingLabel(effectiveProfile.pregnancyDueDate, todayIso),
    [effectiveProfile.pregnancyDueDate, todayIso]
  );
  const monthDays = useMemo(() => buildMonthMatrix(currentMonthDate), [currentMonthDate]);
  const normalizedRangePreview = useMemo(() => {
    if (!periodRangeAnchor) return null;
    if (!periodRangePreviewEnd) return { start: periodRangeAnchor, end: periodRangeAnchor };
    return differenceInDays(periodRangePreviewEnd, periodRangeAnchor) >= 0
      ? { start: periodRangeAnchor, end: periodRangePreviewEnd }
      : { start: periodRangePreviewEnd, end: periodRangeAnchor };
  }, [periodRangeAnchor, periodRangePreviewEnd]);
  const calendarWeeks = useMemo(
    () =>
      monthDays.map((week) =>
        week.map((date) => {
          const dayIso = isoDate(date);
          const record = recordMap.get(dayIso);
          const displayMeta = resolveDayMetaForRecord(
            dayIso,
            todayIso,
            estimatedProfile.lastPeriodStart,
            estimatedProfile.cycleLength,
            estimatedProfile.periodLength,
            record
          );
          const hasRecordDetails = Boolean(record && hasCustomEntryContent(record));
          const matchesFocus =
            calendarFocusMode === 'all'
              ? true
              : calendarFocusMode === 'rules'
                ? displayMeta.kind === 'period' || displayMeta.kind === 'predicted-period'
                : calendarFocusMode === 'notes'
                  ? hasRecordDetails
                  : record
                    ? record.flow === 'Abondant' || record.pain >= 6 || displayMeta.kind === 'period'
                    : displayMeta.kind === 'predicted-period';
          const isRangePreview = Boolean(
            normalizedRangePreview &&
              differenceInDays(dayIso, normalizedRangePreview.start) >= 0 &&
              differenceInDays(normalizedRangePreview.end, dayIso) >= 0
          );
          return {
            dayIso,
            dayNumber: date.getDate(),
            displayMeta,
            isCurrentMonth: date.getMonth() === currentMonthDate.getMonth(),
            hasRecordDetails,
            matchesFocus,
            isRangeAnchor: dayIso === periodRangeAnchor,
            isRangePreview,
            isRangePreviewStart: normalizedRangePreview?.start === dayIso,
            isRangePreviewEnd: normalizedRangePreview?.end === dayIso,
            isSelected: dayIso === selectedDate,
          };
        })
      ),
    [
      currentMonthDate,
      estimatedProfile.cycleLength,
      estimatedProfile.lastPeriodStart,
      estimatedProfile.periodLength,
      monthDays,
      calendarFocusMode,
      periodRangeAnchor,
      normalizedRangePreview,
      recordMap,
      selectedDate,
      todayIso,
    ]
  );
  const avgPain = useMemo(() => averagePain(records), [records]);
  const avgSleep = useMemo(() => averageSleep(records), [records]);
  const avgPeriodLength = useMemo(() => getPeriodLengthAverage(records), [records]);
  const recentRecords = useMemo(() => getRecentRecords(records, 5), [records]);
  const dominantSymptoms = useMemo(() => getDominantSymptoms(records), [records]);
  const flowDistribution = useMemo(() => getFlowDistribution(records), [records]);
  const flowAnomalies = useMemo(() => getFlowAnomalies(records, estimatedProfile), [records, estimatedProfile]);
  const painTrend = useMemo(() => getPainTrend(records), [records]);
  const monthlyHistory = useMemo(() => getMonthlyHistory(records), [records]);
  const trackedDays = records.length;
  const periodDays = useMemo(() => countPeriodEntries(records), [records]);
  const displayedPeriodLength = avgPeriodLength || estimatedProfile.periodLength;
  const shouldShowTrackingSetup = !isPregnancyMode && !hasCycleReference;
  const selectedRecordHasDetails = Boolean(selectedRecord && hasCustomEntryContent(selectedRecord));
  const selectedMeta = useMemo(
    () =>
      hasCycleReference
        ? resolveDayMetaForRecord(
            selectedDate,
            todayIso,
            estimatedProfile.lastPeriodStart,
            estimatedProfile.cycleLength,
            estimatedProfile.periodLength,
            selectedRecord
          )
        : buildUnconfiguredDayMeta(selectedDate, todayIso, selectedRecord),
    [
      hasCycleReference,
      estimatedProfile.cycleLength,
      estimatedProfile.lastPeriodStart,
      estimatedProfile.periodLength,
      selectedDate,
      selectedRecord,
      todayIso,
    ]
  );

  // — UI handlers —
  function togglePeriodSelectionMode() {
    setIsPeriodSelectionMode((current) => !current);
    setPeriodRangeAnchor(null);
    setPeriodRangePreviewEnd(null);
    cycleRecords.setEntryMessage('');
  }

  function selectPeriodMarkMode(mode: PeriodMarkMode) {
    setPeriodMarkMode(mode);
    setPeriodRangeAnchor(null);
    setPeriodRangePreviewEnd(null);
    cycleRecords.setEntryMessage('');
  }

  function shiftMonth(offset: number) {
    startTransition(() => setMonthCursor((current) => current + offset));
  }

  function selectDay(dayIso: string) {
    startTransition(() => setSelectedDate(dayIso));
  }

  async function handlePeriodCalendarPress(dayIso: string) {
    selectDay(dayIso);

    if (periodMarkMode === 'single') {
      setPeriodRangeAnchor(null);
      setPeriodRangePreviewEnd(null);
      await cycleRecords.togglePeriodDay(dayIso);
      return;
    }

    if (!periodRangeAnchor) {
      setPeriodRangeAnchor(dayIso);
      setPeriodRangePreviewEnd(null);
      cycleRecords.setEntryMessage('Date de début enregistrée. Choisis maintenant la date de fin.');
      return;
    }

    setPeriodRangePreviewEnd(dayIso);
    cycleRecords.setEntryMessage('Plage prête. Vérifie le surlignage puis valide.');
  }

  function clearPeriodRangePreview() {
    setPeriodRangeAnchor(null);
    setPeriodRangePreviewEnd(null);
    cycleRecords.setEntryMessage('');
  }

  async function confirmPeriodRangePreview() {
    if (!periodRangeAnchor || !periodRangePreviewEnd) return;
    try {
      await cycleRecords.applyPeriodRange(periodRangeAnchor, periodRangePreviewEnd);
    } catch {
      cycleRecords.setEntryMessage("La mise à jour de la plage a échoué. Réessaie dans quelques instants.");
    } finally {
      setPeriodRangeAnchor(null);
      setPeriodRangePreviewEnd(null);
    }
  }

  async function resetApplication() {
    try {
      await AsyncStorage.multiRemove([
        CYCLE_PROFILE_STORAGE_KEY,
        CYCLE_RECORDS_STORAGE_KEY,
        MEDICAL_REMINDERS_STORAGE_KEY,
        LAST_PERIOD_REFERENCE_CONFIRMED_STORAGE_KEY,
      ]);
      cycleRecords.reset();
      cycleProfile.reset();
      medRem.reset();
      setIsPeriodSelectionMode(false);
      setPeriodMarkMode('single');
      setCalendarFocusMode('all');
      setPeriodRangeAnchor(null);
      setPeriodRangePreviewEnd(null);
      setSelectedDate(todayIso);
      setMonthCursor(0);
    } catch {
      cycleProfile.setProfileMessage("La réinitialisation a échoué. Réessaie dans quelques instants.");
    }
  }

  // — Confirmation handlers —
  function handleDeleteEntry() {
    Alert.alert(
      "Supprimer l'entrée",
      'Cette journée sera effacée définitivement. Confirmer ?',
      [
        { text: 'Annuler', style: 'cancel' },
        { text: 'Supprimer', style: 'destructive', onPress: () => void cycleRecords.deleteEntry(selectedDate) },
      ]
    );
  }

  function handleResetApplication() {
    Alert.alert(
      "Réinitialiser l'application",
      'Toutes les données et le profil seront effacés définitivement. Cette action est irréversible.',
      [
        { text: 'Annuler', style: 'cancel' },
        { text: 'Réinitialiser', style: 'destructive', onPress: () => void resetApplication() },
      ]
    );
  }

  async function handleImportData() {
    try {
      const result = await pickAndParseCsv();
      if (!result) return;

      if (result.records.length === 0) {
        Alert.alert(
          'Import impossible',
          "Le fichier choisi ne contient aucune entrée reconnue. Vérifie qu'il s'agit bien d'un export BaddieBlood au format CSV."
        );
        return;
      }

      const importedDates = new Set(result.records.map((record) => record.date));
      const merged = [...records.filter((record) => !importedDates.has(record.date)), ...result.records];
      await cycleRecords.persistRecords(merged);

      Alert.alert(
        'Import terminé',
        `${result.importedCount} entrée(s) importée(s)` +
          (result.skippedCount ? `, ${result.skippedCount} ligne(s) ignorée(s).` : '.')
      );
    } catch {
      Alert.alert('Erreur', "L'import a échoué. Réessaie dans quelques instants.");
    }
  }

  function handleDeleteMedicalReminder(id: string) {
    Alert.alert(
      'Supprimer le rendez-vous',
      'Ce rendez-vous sera supprimé définitivement. Confirmer ?',
      [
        { text: 'Annuler', style: 'cancel' },
        { text: 'Supprimer', style: 'destructive', onPress: () => void medRem.deleteMedicalReminder(id) },
      ]
    );
  }

  if (!isHydrated) {
    return (
      <SafeAreaView style={styles.loadingScreen}>
        <StatusBar style="light" />
        <ActivityIndicator size="large" color="#ffffff" />
        <Text style={styles.loadingText}>Chargement du suivi personnel...</Text>
      </SafeAreaView>
    );
  }

  if (appLock.isLocked) {
    return <LockScreen onUnlock={() => void appLock.authenticate()} />;
  }

  if (!isProfileConfigured) {
    return (
      <OnboardingScreen
        onboardingStep={onboardingStep}
        profileForm={profileForm}
        profileMessage={profileMessage}
        onProfileFieldChange={(patch) => cycleProfile.updateProfileForm(patch)}
        onPrevious={cycleProfile.goToPreviousOnboardingStep}
        onNext={() => cycleProfile.goToNextOnboardingStep(todayIso)}
        onSave={() => void cycleProfile.saveProfile(todayIso, records, cycleRecords.persistRecords)}
        formatDateTyping={formatFrenchDateTyping}
      />
    );
  }

  const appData = {
    hasCycleReference,
    subtitle: isPregnancyMode
      ? effectiveProfile.pregnancyDueDate
        ? `Bonjour ${effectiveProfile.name}. Tu peux voir ta semaine, tes repères et tes notes du jour en un seul endroit.`
        : 'Mode grossesse activé. Renseigne la date prévue pour afficher tes repères de progression.'
      : hasCycleReference
        ? `Bonjour ${effectiveProfile.name}. Tu peux consulter ton calendrier, tes repères et tes notes du jour en un seul endroit.`
        : 'Commence par configurer ton profil pour afficher tes repères et enregistrer tes journées.',
    todayCycleDay,
    todayCyclePhase,
    nextPeriodValue: isPregnancyMode ? pregnancyDueDateLabel : hasCycleReference ? formatDateLongWithYear(nextPeriodStart) : 'À configurer',
    nextPeriodHint: isPregnancyMode
      ? pregnancyWeeksRemainingLabel === 'À renseigner'
        ? 'Ajoute ta date prévue dans le profil pour activer le suivi de grossesse.'
        : `Encore ${pregnancyWeeksRemainingLabel} avant le terme.`
      : hasCycleReference
        ? `Dans ${nextPeriodInDays} jours selon ton profil actuel.`
        : "Ajoute ton profil dans l'onglet Profil pour activer les prévisions.",
    fertileValue: isPregnancyMode ? pregnancyStage.fruitEmoji : hasCycleReference ? formatDateLongWithYear(fertileWindow.start) : 'À configurer',
    fertileHint: isPregnancyMode
      ? `${pregnancyStage.fruitLabel} - ${pregnancyStage.sizeLabel}`
      : hasCycleReference
        ? `Jusqu'au ${formatDateLongWithYear(fertileWindow.end)}.`
        : 'Visible après configuration du cycle.',
    shouldShowTrackingSetup,
    profileForm,
    trackingSetupMessage,
    isProfileConfigured,
    isPregnancyMode,
    pregnancyStage,
    pregnancyDueDateLabel,
    pregnancyWeeksRemainingLabel,
    nextPeriodStart,
    fertileWindow,
    estimatedProfile,
    displayedPeriodLength,
    avgPain,
    cyclePhase,
    cycleDay,
    monthLabel,
    isPeriodSelectionMode,
    periodMarkMode,
    calendarFocusMode,
    periodRangeAnchor,
    periodRangePreviewEnd,
    calendarWeeks,
    selectedDate,
    selectedMeta,
    selectedRecord,
    trackedDays,
    periodDays,
    avgSleep,
    dominantSymptoms,
    flowDistribution,
    flowAnomalies,
    monthComparison,
    painTrend,
    monthlyHistory,
    recentRecords,
    profileMessage,
    medicalReminderForm: medRem.medicalReminderForm,
    medicalReminders: medRem.sortedMedicalReminders,
    medicalReminderMessage: medRem.medicalReminderMessage,
    shiftMonth,
    onToggleSelectionMode: togglePeriodSelectionMode,
    onSelectPeriodMarkMode: selectPeriodMarkMode,
    onSelectCalendarFocusMode: setCalendarFocusMode,
    onCalendarDayPress: (dayIso: string) => void handlePeriodCalendarPress(dayIso),
    onConfirmRangePreview: () => void confirmPeriodRangePreview(),
    onClearRangePreview: clearPeriodRangePreview,
    onSelectDay: selectDay,
    getRelativeEnergyLabel: getRelativeEnergy,
    onLastPeriodStartChange: (value: string) => cycleProfile.updateProfileForm({ lastPeriodStart: formatFrenchDateTyping(value) }),
    onLastPeriodEndChange: (value: string) => cycleProfile.updateProfileForm({ lastPeriodEnd: formatFrenchDateTyping(value) }),
    onContinueToTracking: () => void cycleProfile.saveLastPeriodReference(records, cycleRecords.persistRecords),
    onProfileFieldChange: (patch: Parameters<typeof cycleProfile.updateProfileForm>[0]) => cycleProfile.updateProfileForm(patch),
    onSwitchTrackingMode: (mode: Parameters<typeof cycleProfile.updateProfileForm>[0]['trackingMode']) => cycleProfile.updateProfileForm({ trackingMode: mode }),
    onFormatDateFieldChange: (field: 'lastPeriodStart' | 'lastPeriodEnd', value: string) =>
      cycleProfile.updateProfileForm(field === 'lastPeriodStart' ? { lastPeriodStart: formatFrenchDateTyping(value) } : { lastPeriodEnd: formatFrenchDateTyping(value) }),
    onSaveProfile: () => void cycleProfile.saveProfile(todayIso, records, cycleRecords.persistRecords),
    formatDateTyping: formatFrenchDateTyping,
    onMedicalReminderFieldChange: medRem.updateMedicalReminderForm,
    onSaveMedicalReminder: () => void medRem.saveMedicalReminder(),
    onDeleteMedicalReminder: handleDeleteMedicalReminder,
    onToggleMedicalReminderCompleted: (id: string) => void medRem.toggleMedicalReminderCompleted(id),
    onReset: handleResetApplication,
    nextPeriodInDays,
    onExportData: () => exportCycleData(records, profile),
    onImportData: () => void handleImportData(),
    themeScheme,
    onToggleTheme,
    isLockEnabled: appLock.isLockEnabled,
    isLockSupported: appLock.isLockSupported,
    onToggleLock: (enabled: boolean) => void appLock.setLockEnabled(enabled),
  };

  return (
    <AppDataContext.Provider value={appData}>
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{
          headerTintColor: c.textPrimary,
          headerStyle: { backgroundColor: c.bgCardAlt },
          headerShadowVisible: false,
          contentStyle: { backgroundColor: c.bg },
        }}
      >
        <Stack.Screen name="Home" options={{ headerShown: false }}>
          {() => <MainDashboardScreen />}
        </Stack.Screen>
        <Stack.Screen
          name="DayEntry"
          options={{ title: 'Fiche du jour', animation: 'slide_from_right' }}
        >
          {() => (
            <DayEntryScreen
              isPregnancyMode={isPregnancyMode}
              selectedDate={selectedDate}
              selectedMeta={selectedMeta}
              selectedRecord={selectedRecord}
              selectedRecordHasDetails={selectedRecordHasDetails}
              cycleDay={cycleDay}
              cyclePhase={cyclePhase}
              pregnancyStage={pregnancyStage}
              pregnancyDueDateLabel={pregnancyDueDateLabel}
              pregnancyWeeksRemainingLabel={pregnancyWeeksRemainingLabel}
              entryForm={entryForm}
              entryMessage={entryMessage}
              flowOptions={flowOptions}
              painOptions={painOptions}
              moodPresets={moodPresets}
              symptomCatalog={symptomCatalog}
              onEntryFieldChange={cycleRecords.updateEntryForm}
              onToggleSymptom={cycleRecords.toggleSymptom}
              onSaveEntry={() => void cycleRecords.saveEntry(selectedDate)}
              onDeleteEntry={handleDeleteEntry}
            />
          )}
        </Stack.Screen>
      </Stack.Navigator>
    </NavigationContainer>
    </AppDataContext.Provider>
  );
}

export default function App() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <ThemeProvider>
        <ErrorBoundary>
          <AppRoot />
        </ErrorBoundary>
      </ThemeProvider>
    </GestureHandlerRootView>
  );
}
