import { StyleSheet } from 'react-native';
import { type AppColors } from './colors';

function createStyles(c: AppColors) {
  return StyleSheet.create({
  loadingScreen: {
    flex: 1,
    backgroundColor: c.primary,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  loadingText: {
    color: c.white,
    fontSize: 16,
    fontWeight: '600',
  },
  keyboardAvoider: {
    flex: 1,
  },
  onboardingScreen: {
    flex: 1,
    backgroundColor: c.bg,
  },
  onboardingContent: {
    paddingBottom: 40,
  },
  onboardingHero: {
    backgroundColor: c.primary,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 36,
    overflow: 'hidden',
  },
  onboardingTitle: {
    color: c.bgCardAlt,
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 12,
    maxWidth: 300,
  },
  onboardingSubtitle: {
    color: c.heroSubtitle,
    fontSize: 16,
    lineHeight: 24,
    maxWidth: 340,
  },
  onboardingBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  onboardingBadge: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  onboardingBadgeText: {
    color: c.bgCardMuted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  onboardingFeatureList: {
    marginTop: 24,
    gap: 12,
  },
  onboardingProgressRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 24,
    marginBottom: 12,
  },
  onboardingProgressDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  onboardingProgressDotActive: {
    backgroundColor: c.white,
  },
  onboardingProgressTrack: {
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    overflow: 'hidden',
  },
  onboardingProgressFill: {
    height: '100%',
    backgroundColor: c.actionBg,
    borderRadius: 999,
  },
  onboardingFeature: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 22,
    padding: 16,
  },
  onboardingFeatureTitle: {
    color: c.white,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  onboardingFeatureText: {
    color: c.textOnDark,
    fontSize: 14,
    lineHeight: 20,
  },
  onboardingFeatureSoft: {
    backgroundColor: c.bgCard,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  onboardingFeatureSoftTitle: {
    color: c.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  onboardingFeatureSoftText: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  onboardingHintCard: {
    backgroundColor: c.accentSandBg,
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  onboardingHintTitle: {
    color: c.textStrong,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  onboardingHintText: {
    color: c.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  medicalReminderList: {
    marginTop: 18,
    gap: 12,
  },
  medicalReminderListTitle: {
    color: c.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  medicalReminderItem: {
    backgroundColor: c.bgCard,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: c.border,
    gap: 10,
  },
  medicalReminderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  medicalReminderHeading: {
    flex: 1,
  },
  medicalReminderTitle: {
    color: c.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  medicalReminderCategory: {
    color: c.textTertiary,
    fontSize: 12,
    fontWeight: '700',
  },
  medicalReminderDelete: {
    color: c.primaryMid,
    fontSize: 12,
    fontWeight: '800',
  },
  medicalReminderNotes: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  onboardingTipCard: {
    backgroundColor: c.bgCardMuted,
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: c.border,
    shadowColor: c.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  onboardingTipTitle: {
    color: c.textPrimary,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 6,
  },
  onboardingTipText: {
    color: c.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  safeArea: {
    flex: 1,
    backgroundColor: c.bg,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  hero: {
    backgroundColor: c.primary,
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 24,
    overflow: 'hidden',
  },
  heroGlowPrimary: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: c.actionBg,
    opacity: 0.28,
    top: -40,
    right: -60,
  },
  heroGlowSecondary: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: c.accentGoldBg,
    opacity: 0.24,
    bottom: -40,
    left: -30,
  },
  sparkleLarge: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.7)',
    top: 38,
    right: 108,
  },
  sparkleMedium: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(255,210,235,0.95)',
    top: 74,
    right: 76,
  },
  sparkleTiny: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,240,196,0.95)',
    top: 58,
    right: 58,
  },
  eyebrow: {
    display: 'none',
  },
  onboardingEyebrow: {
    color: c.borderCard,
    fontSize: 13,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  heroKicker: {
    color: c.borderCard,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  heroLogo: {
    width: 150,
    height: 150,
    alignSelf: 'center',
    marginBottom: 12,
    borderRadius: 28,
  },
  heroSubtitle: {
    color: c.heroSubtitle,
    fontSize: 17,
    lineHeight: 24,
    maxWidth: 360,
  },
  heroStatsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  metricPill: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,220,240,0.18)',
  },
  metricPillLabel: {
    color: c.borderCard,
    fontSize: 12,
    marginBottom: 4,
  },
  metricPillValue: {
    color: c.bgCardAlt,
    fontSize: 17,
    fontWeight: '700',
  },
  heroSummary: {
    marginTop: 18,
    gap: 14,
  },
  heroSummaryCard: {
    backgroundColor: c.bgCard,
    borderRadius: 26,
    padding: 18,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  heroSummaryLabel: {
    color: c.textStrong,
    fontSize: 13,
    marginBottom: 6,
  },
  heroSummaryValue: {
    color: c.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 4,
  },
  heroSummaryHint: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  profileFloatingStack: {
    position: 'absolute',
    top: 14,
    right: 14,
    gap: 10,
    zIndex: 20,
  },
  quickMenuWrap: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 20,
    alignItems: 'flex-end',
    gap: 10,
  },
  quickMenuButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.heroKicker,
    borderWidth: 1,
    borderColor: c.primary,
    shadowColor: c.textPrimary,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  quickMenuButtonActive: {
    backgroundColor: c.primary,
    borderColor: c.primary,
  },
  quickMenuPanel: {
    minWidth: 144,
    backgroundColor: c.bgCard,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: c.borderCard,
    padding: 8,
    shadowColor: c.textPrimary,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  quickMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
  },
  quickMenuItemPressed: {
    backgroundColor: c.accentRoseBgAlt,
  },
  quickMenuItemActive: {
    backgroundColor: c.actionBg,
  },
  quickMenuItemIcon: {
    fontSize: 18,
  },
  quickMenuItemIconActive: {
    color: c.white,
  },
  quickMenuItemText: {
    color: c.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  quickMenuItemTextActive: {
    color: c.white,
  },
  profileFloatingButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.heroKicker,
    borderWidth: 1,
    borderColor: c.primary,
    shadowColor: c.textPrimary,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  profileFloatingButtonActive: {
    backgroundColor: c.primary,
    borderColor: c.primary,
  },
  profileFloatingButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  profileFloatingIcon: {
    fontSize: 24,
    color: c.primary,
  },
  profileFloatingIconActive: {
    color: c.white,
  },
  profileFloatingButtonCompact: {
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  tabBarWrap: {
    paddingHorizontal: 20,
    marginTop: -18,
    zIndex: 2,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: c.bgCard,
    borderRadius: 24,
    padding: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.09,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    paddingVertical: 12,
  },
  tabButtonSelected: {
    backgroundColor: c.actionBg,
  },
  tabButtonText: {
    color: c.textMuted,
    fontWeight: '700',
  },
  tabButtonTextSelected: {
    color: c.white,
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 26,
  },
  sectionTitleWrap: {
    marginBottom: 14,
    paddingLeft: 14,
    borderLeftWidth: 4,
    borderLeftColor: '#ff78b6',
  },
  sectionTitle: {
    fontSize: 23,
    color: c.textPrimary,
    fontWeight: '800',
    marginBottom: 4,
  },
  sectionSubtitle: {
    color: c.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  infoCard: {
    width: '48%',
    borderRadius: 24,
    padding: 18,
    minHeight: 110,
    justifyContent: 'space-between',
  },
  infoCardLabel: {
    fontSize: 13,
    lineHeight: 18,
  },
  infoCardValue: {
    fontSize: 24,
    fontWeight: '800',
    color: c.textPrimary,
  },
  calendarCard: {
    backgroundColor: c.bgCard,
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  calendarToolsRow: {
    gap: 12,
    marginBottom: 16,
  },
  calendarModeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  calendarToolButton: {
    alignSelf: 'flex-start',
    backgroundColor: c.accentRoseBgAlt,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  calendarToolButtonActive: {
    backgroundColor: c.actionBg,
  },
  calendarToolButtonText: {
    color: c.textStrong,
    fontWeight: '700',
    fontSize: 13,
  },
  calendarToolButtonTextActive: {
    color: c.white,
  },
  calendarHintText: {
    color: c.textMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  monthButton: {
    backgroundColor: c.accentRoseBgAlt,
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthButtonText: {
    color: c.textStrong,
    fontWeight: '700',
    fontSize: 18,
  },
  calendarMonthLabel: {
    fontSize: 18,
    fontWeight: '800',
    color: c.textPrimary,
  },
  weekdaysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  weekdayText: {
    width: '13.5%',
    textAlign: 'center',
    color: c.textTertiary,
    fontSize: 12,
    fontWeight: '700',
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  dayCell: {
    width: '13.5%',
    aspectRatio: 0.9,
    borderRadius: 18,
    position: 'relative',
    overflow: 'visible',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.bgCardAlt,
    borderWidth: 1,
    borderColor: c.border,
  },
  dayCellFiltered: {
    opacity: 0.7,
  },
  dayCellOutOfMonth: {
    opacity: 0.48,
  },
  dayCellPeriod: {
    backgroundColor: c.borderCard,
    borderColor: c.primaryMid,
  },
  dayCellPredicted: {
    backgroundColor: c.accentRoseBg,
    borderColor: c.shadow,
    borderStyle: 'dashed',
  },
  dayCellFertile: {
    backgroundColor: c.accentGoldBg,
    borderColor: c.accentGoldFg,
  },
  dayCellToday: {
    borderColor: c.primary,
    borderWidth: 2,
  },
  dayCellAnchor: {
    borderColor: c.actionBg,
    borderWidth: 2.5,
  },
  dayCellSelected: {
    transform: [{ scale: 1.04 }],
    shadowColor: c.actionBg,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  dayNumber: {
    color: c.textMuted,
    fontWeight: '700',
    fontSize: 15,
  },
  dayNumberMuted: {
    color: c.textTertiary,
  },
  dayNumberStrong: {
    color: c.textStrong,
  },
  dayNumberSelected: {
    color: c.primary,
  },
  dayNumberRangePreview: {
    color: c.textPrimary,
  },
  dayMarkersRow: {
    flexDirection: 'row',
    gap: 3,
    marginTop: 4,
  },
  rangePreviewFill: {
    position: 'absolute',
    left: -6,
    right: -6,
    top: '28%',
    bottom: '28%',
    backgroundColor: c.rangePreviewBg,
    zIndex: 0,
  },
  rangePreviewFillStart: {
    left: '16%',
    borderTopLeftRadius: 999,
    borderBottomLeftRadius: 999,
  },
  rangePreviewFillEnd: {
    right: '16%',
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
  },
  rangePreviewFillSingle: {
    left: '16%',
    right: '16%',
    borderRadius: 999,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  dotPeriod: {
    backgroundColor: c.primaryMid,
  },
  dotPredicted: {
    backgroundColor: c.dotPredicted,
  },
  dotFertile: {
    backgroundColor: c.dotFertile,
  },
  dotToday: {
    backgroundColor: c.primary,
  },
  legendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: 16,
  },
  calendarStateRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
    marginBottom: 4,
  },
  calendarStateChip: {
    flex: 1,
    backgroundColor: c.bg,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#e8b9cf',
  },
  calendarStateChipSoft: {
    backgroundColor: c.bgCardAlt,
  },
  calendarStateLabel: {
    color: c.textTertiary,
    fontSize: 12,
    marginBottom: 4,
  },
  calendarStateValue: {
    color: c.textPrimary,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
  },
  calendarFocusText: {
    color: c.textTertiary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendText: {
    color: c.textMuted,
    fontSize: 13,
  },
  rangePreviewCard: {
    backgroundColor: c.bg,
    borderRadius: 22,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  rangePreviewTitle: {
    color: c.primaryMid,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  rangePreviewText: {
    color: c.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  rangePreviewActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  comparisonCard: {
    backgroundColor: c.white,
    borderRadius: 28,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  comparisonHeader: {
    flexDirection: 'row',
    gap: 12,
  },
  comparisonMonth: {
    flex: 1,
    backgroundColor: c.bgCardMuted,
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: c.border,
  },
  comparisonMonthLabel: {
    color: c.textTertiary,
    fontSize: 12,
    marginBottom: 4,
  },
  comparisonMonthValue: {
    color: c.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  comparisonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  comparisonMetric: {
    width: '47%',
    backgroundColor: c.bgCardMuted,
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: c.border,
  },
  comparisonMetricLabel: {
    color: c.textTertiary,
    fontSize: 12,
    marginBottom: 4,
  },
  comparisonMetricValue: {
    color: c.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  comparisonMetricDelta: {
    color: '#a35a7f',
    fontSize: 12,
    fontWeight: '700',
  },
  detailCard: {
    backgroundColor: c.white,
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
    gap: 10,
  },
  detailHeaderText: {
    flex: 1,
  },
  detailTitle: {
    fontSize: 22,
    color: c.textPrimary,
    fontWeight: '800',
    marginBottom: 4,
  },
  detailSubtitle: {
    color: c.textSecondary,
    fontSize: 14,
  },
  phaseBadge: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  phaseBadgeText: {
    fontWeight: '800',
    fontSize: 13,
  },
  detailMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  detailBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  detailBadge: {
    backgroundColor: c.bg,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: c.border,
  },
  detailBadgeSoft: {
    backgroundColor: c.bgCardAlt,
  },
  detailBadgeText: {
    color: c.textStrong,
    fontWeight: '800',
    fontSize: 12,
  },
  detailMetric: {
    width: '47%',
    backgroundColor: c.bg,
    borderRadius: 20,
    padding: 14,
  },
  detailMetricLabel: {
    fontSize: 12,
    color: c.textTertiary,
    marginBottom: 4,
  },
  detailMetricValue: {
    fontSize: 18,
    fontWeight: '700',
    color: c.textPrimary,
  },
  notesCard: {
    marginTop: 16,
    backgroundColor: c.bgCardMuted,
    borderRadius: 22,
    padding: 16,
    shadowColor: c.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  notesTitle: {
    color: c.textPrimary,
    fontWeight: '800',
    fontSize: 16,
    marginBottom: 10,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  chip: {
    backgroundColor: c.accentRoseBgAlt,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipText: {
    color: c.textStrong,
    fontWeight: '600',
    fontSize: 13,
  },
  notesBody: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  editorCard: {
    backgroundColor: c.white,
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  editorLabel: {
    color: c.textPrimary,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 10,
  },
  optionWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  selectChip: {
    backgroundColor: c.bg,
    borderColor: c.borderLight,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  selectChipSelected: {
    backgroundColor: c.actionBg,
    borderColor: c.actionBg,
  },
  selectChipText: {
    color: c.textMuted,
    fontWeight: '700',
  },
  selectChipTextSelected: {
    color: c.white,
  },
  textInput: {
    backgroundColor: c.bg,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: c.borderLight,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
    color: c.textPrimary,
  },
  textInputError: {
    borderColor: c.errorFg,
    borderWidth: 1.5,
  },
  notesInput: {
    minHeight: 120,
    paddingTop: 14,
  },
  saveMessage: {
    color: c.saveMessageFg,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  primaryAction: {
    flex: 1,
    backgroundColor: c.actionBg,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryActionText: {
    color: c.white,
    fontWeight: '800',
    fontSize: 15,
  },
  secondaryAction: {
    flex: 1,
    backgroundColor: c.accentRoseBgAlt,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
  },
  secondaryActionText: {
    color: '#a23b71',
    fontWeight: '800',
    fontSize: 15,
  },
  resetBlock: {
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#f7d7e8',
    paddingTop: 18,
  },
  resetTitle: {
    color: c.primary,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  resetText: {
    color: c.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  dangerAction: {
    backgroundColor: '#9b2f67',
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: 'center',
  },
  dangerActionText: {
    color: c.white,
    fontWeight: '800',
    fontSize: 15,
  },
  sheetScreen: {
    flex: 1,
    backgroundColor: c.bg,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 10,
    backgroundColor: c.bgCardAlt,
    borderBottomWidth: 1,
    borderBottomColor: c.borderCard,
  },
  sheetHeaderButton: {
    minWidth: 72,
  },
  sheetHeaderButtonText: {
    color: '#a03c70',
    fontWeight: '800',
    fontSize: 15,
  },
  sheetHeaderTitle: {
    color: c.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  sheetHeaderSpacer: {
    minWidth: 72,
  },
  sheetScrollContent: {
    paddingBottom: 40,
  },
  statsCard: {
    backgroundColor: c.white,
    borderRadius: 28,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  anomalyCard: {
    backgroundColor: c.white,
    borderRadius: 28,
    padding: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  anomalyItem: {
    backgroundColor: c.bgCardMuted,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: c.border,
  },
  anomalyBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 10,
  },
  anomalyBadgeText: {
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  anomalyTitle: {
    color: c.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  anomalyDetail: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  anomalyMeta: {
    marginTop: 8,
    color: c.textTertiary,
    fontSize: 12,
    fontWeight: '700',
  },
  anomalyEmptyState: {
    backgroundColor: c.bgCardMuted,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: c.border,
  },
  anomalyEmptyTitle: {
    color: c.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  anomalyEmptyText: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f7d7e8',
    paddingBottom: 12,
  },
  statsLabel: {
    flex: 1,
    color: c.textMuted,
    fontSize: 14,
  },
  statsValue: {
    color: c.textPrimary,
    fontWeight: '800',
    fontSize: 14,
  },
  symptomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  symptomName: {
    color: c.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  symptomBadge: {
    backgroundColor: c.accentGoldBg,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  symptomBadgeText: {
    color: c.accentGoldFg,
    fontWeight: '700',
  },
  dominantSymptomRow: {
    gap: 8,
  },
  dominantSymptomHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  dominantSymptomCount: {
    color: c.accentGoldFg,
    fontSize: 12,
    fontWeight: '800',
  },
  dominantSymptomTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: c.border,
    overflow: 'hidden',
  },
  dominantSymptomFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: c.actionBg,
  },
  chartCard: {
    backgroundColor: c.white,
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: c.borderCard,
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  trendChartRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
    minHeight: 180,
  },
  trendColumn: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  trendColumnTrack: {
    width: '100%',
    maxWidth: 28,
    height: 130,
    justifyContent: 'flex-end',
    backgroundColor: c.bg,
    borderRadius: 999,
    padding: 4,
  },
  trendPainBar: {
    width: '100%',
    borderRadius: 999,
    minHeight: 8,
  },
  trendValueLabel: {
    color: '#8b5a75',
    fontSize: 11,
    fontWeight: '700',
  },
  trendDateLabel: {
    color: c.textSecondary,
    fontSize: 11,
  },
  chartFootnote: {
    color: c.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 16,
  },
  flowDistributionBar: {
    flexDirection: 'row',
    height: 20,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: c.accentRoseBgAlt,
  },
  flowDistributionSegment: {
    height: '100%',
  },
  flowDistributionLegend: {
    gap: 10,
    marginTop: 16,
  },
  flowLegendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  flowLegendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  flowLegendText: {
    color: c.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  monthHistoryItem: {
    backgroundColor: c.bgCardAlt,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#f7d8e8',
  },
  monthHistoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  monthHistoryTitle: {
    color: c.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  monthHistoryBadge: {
    color: '#a03c70',
    fontSize: 12,
    fontWeight: '700',
    backgroundColor: c.accentRoseBgAlt,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  monthHistoryMetrics: {
    gap: 6,
  },
  monthHistoryText: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  emptyText: {
    color: c.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  timelineList: {
    gap: 12,
  },
  timelineItem: {
    backgroundColor: c.bgCard,
    borderRadius: 22,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: c.borderCard,
  },
  timelineDate: {
    alignSelf: 'flex-start',
    backgroundColor: c.accentRoseBgAlt,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  timelineDateText: {
    color: c.textStrong,
    fontWeight: '700',
    fontSize: 12,
  },
  timelineBody: {
    gap: 6,
  },
  timelineTitle: {
    color: c.textPrimary,
    fontWeight: '800',
    fontSize: 15,
  },
  timelineText: {
    color: c.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  chipPanel: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  featureChip: {
    backgroundColor: c.white,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#f6d8e8',
  },
  featureChipText: {
    color: '#8f3a6b',
    fontWeight: '700',
  },
  roadmapList: {
    gap: 12,
  },
  roadmapItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: c.bgCard,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: c.borderCard,
  },
  roadmapIndex: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: c.actionBg,
    color: c.white,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: '800',
    overflow: 'hidden',
    lineHeight: 28,
  },
  roadmapText: {
    color: c.textPrimary,
    fontSize: 15,
    fontWeight: '600',
  },
  });
}

import { light, dark } from './colors';

export const lightStyles = createStyles(light);
export const darkStyles = createStyles(dark);

// Legacy export so existing `import { styles }` still works (always light).
// Components that want dark-mode support should use useAppStyles() instead.
export const styles = lightStyles;
