export type AppColors = {
  bg: string;
  bgCard: string;
  bgCardAlt: string;
  bgCardMuted: string;
  bgInput: string;
  bgHero: string;
  primary: string;
  primaryMid: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  textOnDark: string;
  textMuted: string;
  textStrong: string;
  placeholder: string;
  border: string;
  borderLight: string;
  borderCard: string;
  shadow: string;
  actionBg: string;
  accentRoseBg: string;
  accentRoseBgAlt: string;
  accentRoseFg: string;
  accentGoldBg: string;
  accentGoldFg: string;
  accentBlueBg: string;
  accentBlueFg: string;
  accentSandBg: string;
  accentSandFg: string;
  white: string;
  errorFg: string;
  saveMessageFg: string;
  heroKicker: string;
  heroSubtitle: string;
  heroPill: string;
  // Calendar
  dotPredicted: string;
  dotFertile: string;
  rangePreviewBg: string;
  // Cycle phases
  phaseRulesBg: string;
  phaseRulesFg: string;
  phaseFollBg: string;
  phaseFollFg: string;
  phaseOvulBg: string;
  phaseOvulFg: string;
  phaseLutBg: string;
  phaseLutFg: string;
};

export const light: AppColors = {
  bg: '#fff2f8',
  bgCard: '#fff9fd',
  bgCardAlt: '#fff8fc',
  bgCardMuted: '#fff5fb',
  bgInput: '#fff2f8',
  bgHero: '#7d1d4f',
  primary: '#7d1d4f',
  primaryMid: '#c71f63',
  textPrimary: '#5c1736',
  textSecondary: '#7a6876',
  textTertiary: '#9d7d90',
  textOnDark: '#ffffff',
  textMuted: '#7d6678',
  textStrong: '#a91f60',
  placeholder: '#93a1af',
  border: '#f3d3e2',
  borderLight: '#f2cfe1',
  borderCard: '#ffdbe9',
  shadow: '#c84f87',
  actionBg: '#d94c95',
  accentRoseBg: '#ffdceb',
  accentRoseBgAlt: '#ffe3f0',
  accentRoseFg: '#ca3f82',
  accentGoldBg: '#fff3de',
  accentGoldFg: '#ad7b2d',
  accentBlueBg: '#f5e6f7',
  accentBlueFg: '#8e4aa8',
  accentSandBg: '#fff0f7',
  accentSandFg: '#b14c7b',
  white: '#ffffff',
  errorFg: '#e53e6d',
  saveMessageFg: '#96386d',
  heroKicker: '#ffd1e3',
  heroSubtitle: '#ffe2f0',
  heroPill: 'rgba(255,255,255,0.14)',
  dotPredicted: '#f08fb8',
  dotFertile: '#c99622',
  rangePreviewBg: '#f6b6d0',
  phaseRulesBg: '#fde1e8',
  phaseRulesFg: '#a2325a',
  phaseFollBg: '#fff0da',
  phaseFollFg: '#8b5f16',
  phaseOvulBg: '#dcf5f1',
  phaseOvulFg: '#166765',
  phaseLutBg: '#e6edf5',
  phaseLutFg: '#2d4b68',
};

// Re-exported in useAppStyles.ts — kept here to avoid circular deps
export { light as lightColors, dark as darkColors };

export const dark: AppColors = {
  bg: '#0d0818',
  bgCard: '#160c2a',
  bgCardAlt: '#120a22',
  bgCardMuted: '#0f0820',
  bgInput: '#1e1235',
  bgHero: '#2d1060',
  primary: '#9d4edd',
  primaryMid: '#c77dff',
  textPrimary: '#e8d8ff',
  textSecondary: '#b8a0d8',
  textTertiary: '#8870b0',
  textOnDark: '#ffffff',
  textMuted: '#a08ac0',
  textStrong: '#c4b5fd',
  placeholder: '#7060a0',
  border: '#3d1a70',
  borderLight: '#2a1255',
  borderCard: '#4a2080',
  shadow: '#7c3aed',
  actionBg: '#7c3aed',
  accentRoseBg: '#2d0f50',
  accentRoseBgAlt: '#270d45',
  accentRoseFg: '#e879f9',
  accentGoldBg: '#1e1308',
  accentGoldFg: '#dda050',
  accentBlueBg: '#0e0a2a',
  accentBlueFg: '#a78bfa',
  accentSandBg: '#1c1030',
  accentSandFg: '#c4b5fd',
  white: '#160c2a',
  errorFg: '#f472b6',
  saveMessageFg: '#a78bfa',
  heroKicker: '#d8b4fe',
  heroSubtitle: '#c4b5fd',
  heroPill: 'rgba(255,255,255,0.10)',
  dotPredicted: '#c77dff',
  dotFertile: '#dda050',
  rangePreviewBg: '#2d0f50',
  phaseRulesBg: '#2d0a40',
  phaseRulesFg: '#e879f9',
  phaseFollBg: '#1a0f30',
  phaseFollFg: '#c4b5fd',
  phaseOvulBg: '#1a1035',
  phaseOvulFg: '#d8b4fe',
  phaseLutBg: '#101530',
  phaseLutFg: '#a78bfa',
};
